# Insurance Claim Prediction Project

This project predicts whether a building will have an insurance claim over the insured period using building characteristics. The workflow demonstrates an end-to-end machine learning pipeline, including:

- Data understanding (Notebook 1)
- Exploratory data analysis (EDA) with insights (Notebook 2)
- Data preprocessing and data Modeling and evaluation (Notebook 3)
- Baseline modeling using Logistic Regression and Random Forest
- Hyperparameter tuning with GridSearchCV
- Model evaluation using accuracy, ROC-AUC, and confusion matrices
- Comparison of model performance with clear interpretation

The project highlights best practices in machine learning, model selection, and result communication, making it suitable for showcasing on GitHub for entry-level data science and machine learning roles.

## PROBLEM STATEMENT 
The objective of this project is to predict the probability that a building will have at least one insurance claim during the insured period, based on its characteristics

## 1. Data Understanding

### Objective
The goal of this notebook is to understand the structure, content and basic characteristics of the insurance dataset before performing any analysis or modelling

## 1.1 Load Libraries
This section import all required python libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## 1.2 Load dataset
1. Load raw dataset
1. display first and last few rows

In [3]:
Train_data = pd.read_csv("Train_data.csv")

In [5]:
Train_data.head() # A look at the first(5)observations of the dataset

,Customer Id,YearOfObservation,Insured_Period,Residential,Building_Painted,Building_Fenced,Garden,Settlement,Building Dimension,Building_Type,Date_of_Occupancy,NumberOfWindows,Geo_Code,Claim
0,H14663,2013,1.0,0,N,V,V,U,290.0,1,1960.0,.,1053,0
1,H2037,2015,1.0,0,V,N,O,R,490.0,1,1850.0,4,1053,0
2,H3802,2014,1.0,0,N,V,V,U,595.0,1,1960.0,.,1053,0
3,H3834,2013,1.0,0,V,V,V,U,2840.0,1,1960.0,.,1053,0
4,H5053,2014,1.0,0,V,N,O,R,680.0,1,1800.0,3,1053,0

In [6]:
Train_data.tail() # A look at the last (5) observations

,Customer Id,YearOfObservation,Insured_Period,Residential,Building_Painted,Building_Fenced,Garden,Settlement,Building Dimension,Building_Type,Date_of_Occupancy,NumberOfWindows,Geo_Code,Claim
7155,H5290,2012,1.000000,1,V,V,V,U,NaN,1,2001.0,.,NaN,0
7156,H5926,2013,1.000000,0,V,V,V,U,NaN,2,1980.0,.,NaN,1
7157,H6204,2016,0.038251,0,V,V,V,U,NaN,1,1992.0,.,NaN,0
7158,H6537,2013,1.000000,0,V,V,V,U,NaN,1,1972.0,.,NaN,0
7159,H7470,2014,1.000000,0,V,V,V,U,NaN,1,2004.0,.,NaN,0

## 1.3 Data structure
* Data types
* shape of the dataset
* column names

In [7]:
Train_data.dtypes

Customer Id            object
YearOfObservation       int64
Insured_Period        float64
Residential             int64
Building_Painted       object
Building_Fenced        object
Garden                 object
Settlement             object
Building Dimension    float64
Building_Type           int64
Date_of_Occupancy     float64
NumberOfWindows        object
Geo_Code               object
Claim                   int64
dtype: object

In [10]:
Train_data.shape # shows number of rows and columns

(7160, 14)

In [9]:
Train_data.columns # shows the varaiables of the columns

Index(['Customer Id', 'YearOfObservation', 'Insured_Period', 'Residential',
       'Building_Painted', 'Building_Fenced', 'Garden', 'Settlement',
       'Building Dimension', 'Building_Type', 'Date_of_Occupancy',
       'NumberOfWindows', 'Geo_Code', 'Claim'],
      dtype='object')

## 1.4 Missing values check
* Identify missing values
* Summary of missing data

In [17]:
Train_data.isnull().sum()# checking for missing values

Customer Id             0
YearOfObservation       0
Insured_Period          0
Residential             0
Building_Painted        0
Building_Fenced         0
Garden                  7
Settlement              0
Building Dimension    106
Building_Type           0
Date_of_Occupancy     508
NumberOfWindows         0
Geo_Code              102
Claim                   0
dtype: int64

In [18]:
Train_data.isnull().sum().sort_values(ascending=False)# contains columns with missing values

Date_of_Occupancy     508
Building Dimension    106
Geo_Code              102
Garden                  7
Customer Id             0
YearOfObservation       0
Insured_Period          0
Residential             0
Building_Painted        0
Building_Fenced         0
Settlement              0
Building_Type           0
NumberOfWindows         0
Claim                   0
dtype: int64

## 1.5 Target variable identification
* Define the target variable
* check target distribution

In [13]:
Train_data['Claim'].value_counts(normalize=True)# check target distribution

Claim
0    0.771788
1    0.228212
Name: proportion, dtype: float64

## 1.6 Duplicate Records
* Check for duplicate rows

In [17]:
Train_data.duplicated().sum() # No duplicate record found

0

## 1.7 Initial Exploratory Data Analysis(EDA)
* Drop identifier column

In [18]:
Train_data = Train_data.drop(columns=['Customer Id'])#we drop "customer id" because it has no analytical value.

In [19]:
Train_data.head()

,YearOfObservation,Insured_Period,Residential,Building_Painted,Building_Fenced,Garden,Settlement,Building Dimension,Building_Type,Date_of_Occupancy,NumberOfWindows,Geo_Code,Claim
0,2013,1.0,0,N,V,V,U,290.0,1,1960.0,.,1053,0
1,2015,1.0,0,V,N,O,R,490.0,1,1850.0,4,1053,0
2,2014,1.0,0,N,V,V,U,595.0,1,1960.0,.,1053,0
3,2013,1.0,0,V,V,V,U,2840.0,1,1960.0,.,1053,0
4,2014,1.0,0,V,N,O,R,680.0,1,1800.0,3,1053,0

## Conclusion
This notebook provided an initial understanding of the dataset structure and quality, forming the foundation for exploratory data analysis